version: "3.5"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
        - ./:/app
    working_dir: /app
    environment:
        - FLASK_APP=app.py
        - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
    mongodata:



